version: '3.4'

services:
  db:
    image: postgres:14.5
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Services/Orders/dbscripts/seed2.sql:/docker-entrypoint-initdb.d/seed.sql

  orders:
    image: ${DOCKER_REGISTRY-}orders
    container_name: orders
    build:
      context: .
      dockerfile: Services/Orders/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=db;Port=5432;Username=postgres;Password=postgres;Database=orderDB"
    depends_on:
      - db
    ports:
      - 8080:80

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8081:8080

volumes:
  postgres_data:
