version: '3.4'

services:
  orderdb:
    image: postgres:14.5
    container_name: orderdb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: orderDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Services/Orders/dbscripts/seed2.sql:/docker-entrypoint-initdb.d/seed.sql

  orders:
    image: ${DOCKER_REGISTRY-}orders
    container_name: orders
    build:
      context: .
      dockerfile: Services/Orders/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionString:DefaultConnection=Server=localhost;Port=5432;Username=postgres;Password=postgres;Database=orderDB"
    depends_on:
      - orderdb
    ports:
      - 8080:80

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8081:8080

volumes:
  postgres_data:
