version: '3.4'

services:
  ratedb:
    image: postgres:14.5
    container_name: ratedb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: orderDB
    volumes:
       - postgres_data:/var/lib/postgresql/data
       - ./grpc/seed2.sql:/docker-entrypoint-initdb.d/seed.sql
  labgrpca:
    image: ${DOCKER_REGISTRY-}labgrpca
    build:
      context: .
      dockerfile: grpc/Dockerfile
    ports:
      - "8888:443"
      - "8887:80"
  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  postgres_data: